Trying to include the advanced maths package in the jar so that we can refer to it at runtime: at the moment I get NoClassDefFoundError the first time I try to do something with one of the classes in that library, but at least the inclusion instructions in the POM.xml let ANIMO get loaded by Cytoscape. It looks like more instructions are needed?